{
  "hash": "2e7a6379b63485d6f9ffb8cef12df2d6",
  "result": {
    "engine": "knitr",
    "markdown": "# Graphical Summaries {#ch2}\n\n::: callout-note\n### Learning objectives\n\nBy the end of this chapter, you should be able to:\n\n-   explain why graphical summaries are useful for understanding data,\n-   distinguish between cardinal, ordinal, and nominal data,\n-   identify appropriate graphical representations for different types of data,\n-   construct and interpret histograms correctly, including those with unequal class intervals,\n-   explain how histogram areas represent percentages or probabilities,\n-   recognize common histogram shapes such as symmetric, skewed, unimodal, and bimodal distributions.\n:::\n\nA defining characteristic of today’s information age is the abundance of data. Data in their raw form can be difficult to comprehend. One useful way to summarize a mass of data is through **graphical or pictorial representations**.\n\nMany such graphs—pie charts, bar graphs, and so on—are easy to understand and commonly used. In this chapter, we focus on the **most important graphical representation in statistics: the histogram**.[^ch2-1]{.sidenote}\n\n[^ch2-1]: Why might graphs be more informative than tables when data sets are large?\n\n::: callout-note\n### Big picture\n\nGraphs help us *see* patterns in data that are often invisible in raw numbers.\n:::\n\n## Types of data\n\nData are not all the same. A helpful way to think about them is in **three levels**:\n\n-   **Cardinal data**\n-   **Ordinal data**\n-   **Nominal data**\n\nOnce you know which kind of data you have, it becomes much easier to choose sensible statistics and graphs.\n\n### Cardinal data\n\n**Cardinal data** (sometimes further divided into *interval* and *ratio* data) are represented by real numbers—such as heights, weights, and prices. These are **quantitative (numerical)** data, so arithmetic operations are meaningful.\n\nFor example, with heights or prices, it makes sense to say someone is *twice as tall* or that one item is *three times as expensive*.\n\n### Ordinal data\n\n**Ordinal data** are values for which **only the order (ranking)** is meaningful. A common example is a course evaluation scale such as:\n\n-   Poor = 1\\\n-   Fair = 2\\\n-   Good = 3\\\n-   Very Good = 4\\\n-   Excellent = 5\n\nHere, arithmetic operations usually do **not** make sense. It would sound strange, for instance, to say:\n\n`2 × Fair = Very Good`.\n\nStill, ordinal data are useful because the ranking is clear: *Excellent* (5) is better than *Very Good* (4), which is better than *Good* (3), and so on. Importantly, that ordering remains the same even if we changed the numbers used to label the categories.\n\n### Nominal data\n\n**Nominal data** are usually **qualitative or categorical**. The numbers attached to categories serve only as labels. For example, marital status might be coded as:\n\n-   Single = 1\\\n-   Married = 2\\\n-   Divorced = 3\\\n-   Widowed = 4\n\nBecause these numbers are arbitrary, arithmetic operations are meaningless. It is absurd, for example, to say:\n\n`married ÷ 2 = single`.\n\nWith categorical data, the main meaningful calculation is **counting**—how often each category occurs. We often summarize nominal data using a **frequency distribution**, or a **relative frequency distribution** showing proportions.\n\n::: callout-important\n### Key idea\n\nThe *type* of data determines which graphs and summaries make sense.\n:::\n\n### Why this matters\n\nKeeping the data type in mind helps determine which statistical tools—graphical or otherwise—are appropriate. Among graphical techniques, we will emphasize the **histogram**, which plays a central role in statistics and probability.\n\n## The histogram\n\nTo understand how a histogram works, let us look at a concrete example.\\\n@tbl-income shows the **percentage of families** in each **income class interval**, measured in thousands of baht per year, for Bangkok residents in a recent year.\n\n::: {#tbl-income}\n| Income (Baht '000) | Percentage |\n|--------------------|------------|\n| 0–30               | 1          |\n| 30–60              | 3          |\n| 60–90              | 6          |\n| 90–120             | 10         |\n| 120–150            | 11         |\n| 150–210            | 24         |\n| 210–270            | 20         |\n| 270–390            | 18         |\n| 390–600            | 5          |\n| Over 600           | 1          |\n\nAnnual income for a sample of Bangkok residents\n:::\n\nTo construct a histogram from @tbl-income, the **first step** is to draw the **horizontal axis**, representing income.\n\nA common mistake at this stage is to give **each class interval the same width**, regardless of its actual size. This leads to a misleading picture.\n\n![](figs/ch2/vert-a.png)\n\nInstead, the horizontal axis should reflect the *actual width* of each income class, as shown below.[^ch2-2]\n\n[^ch2-2]: Class intervals need not be equal; wider intervals may be used where data are sparse.\n\n![](figs/ch2/vert-b.png)\n\nThe next step is to draw the blocks. Students often make the mistake of setting the height of each block equal to the percentage in the table. The figure below shows what happens if this is done.\n\n![](figs/ch2/hist-a.png)\n\nThis gives a misleading impression—for example, it appears that there are more families earning over 390,000 baht than under 120,000 baht, which is not correct.\n\n::: callout-warning\n### Common pitfall\n\nIn a histogram, **heights alone do not represent frequencies** when class widths differ.\n:::\n\nBecause the class intervals are unequal, the height of each block must be calculated as:\n\n> percentage ÷ class width (relative length)\n\nFor example, the interval 150–210 spans two 30,000-baht units. Dividing 24% by 2 gives the correct height. The vertical axis is therefore a **density scale** (percent per 30,000). The correct histogram is:\n\n![Correct Histogram](figs/ch2/hist-b.png){#fig-correcthist fig-align=\"center\"}\n\nIn a histogram: - **areas** represent percentages (or probabilities) - **heights** represent crowding per horizontal unit\n\nAn important property to remember is that the **total area under the histogram must equal 100 percent**.\n\n::: callout-important\n### Key idea\n\nHistograms represent data through *areas*, not just heights.\n:::\n\n## Shapes of histograms\n\nHistograms come in many shapes. A histogram is **symmetric** if the two sides mirror each other around a central vertical line. The most famous symmetric histogram is the **Gaussian (normal) distribution**.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Gaussian Distribution](Ch2_files/figure-pdf/fig-gaussian-1.pdf){#fig-gaussian width=75%}\n:::\n:::\n\n\n\n\n\n\nA **skewed histogram** is one with a long tail extending either to the right or to the left:\n\n![](figs/ch2/skewed.png){fig-align=\"center\"}\n\nHistograms can also be **unimodal**, with a single peak, or **bimodal**, with two peaks, and so on.\n\n![](figs/ch2/modal.png){fig-align=\"center\"}\n\n::: callout-important\n### Key idea\n\nThe *shape* of a histogram provides valuable information about the distribution of the data, beyond what summary statistics alone can reveal.\n:::\n\n## Quantitative and qualitative variables\n\nA **variable** is a characteristic that can vary from one individual to another.\\\nFor example, if we ask *“How old are you?”*, the variable of interest is **age**.\\\nIn this case, age is a *quantitative variable*, since it is usually expressed as a number.\n\nIn other cases, the question might be *“What color is your hair?”*\\\nHere, the variable is a *qualitative variable*, because the responses describe categories rather than numerical magnitudes.\n\nA useful distinction among quantitative variables is between **discrete** and **continuous** variables.\n\n-   A **discrete variable** takes on values in fixed steps. An example is the number of children in a household.\n-   A **continuous variable** can take on any value along a real line, such as height, weight, or income.\n\nWorking with quantitative variables is usually straightforward. Qualitative variables, however, are often handled by assigning **arbitrary numerical codes** to the possible responses. In practice, this means that a researcher codes qualitative information into nominal numerical data.\n\nFor example, a course evaluation might be coded as:\n\n-   Poor = 1\\\n-   Fair = 2\\\n-   Good = 3\\\n-   Very Good = 4\\\n-   Excellent = 5\n\n::: callout-warning\n### Common pitfall\n\nDo not treat coded qualitative variables as numerical measurements. Arithmetic operations on these codes usually have no meaningful interpretation.\n:::\n\nIt is important to remember that these numbers are **labels rather than true measurements**, and arithmetic operations on them may not be meaningful.\n\nIt is also useful to distinguish between different **data structures**, such as:\n\n-   **Cross-sectional data**, which observe many individuals at a single point in time\\\n-   **Time-series data**, which track a single unit over time\\\n-   **Panel (or longitudinal) data**, which follow multiple individuals over time\n\nThe statistical tools available to the researcher often depend on which of these data structures is being used.\n\n::: callout-note\n### Pause and think\n\nWhich of the variables you encounter in daily life—income, grades, or job titles—are quantitative, and which are qualitative?\n:::\n\n## Other graphical representations of data\n\nThere are many graphical methods available for representing data. Some, such as **bar graphs** and **pie charts**, are widely known. Others, such as the **stem-and-leaf plot** or the **ogive**, are more specialized.\n\nMost introductory statistics textbooks discuss a variety of graphical summaries, and interested readers are encouraged to consult these sources.[^ch2-3]\n\n[^ch2-3]: Some recommended texts include Peck, Olsen, and Devore (2005, Chapter 3), Utts and Heckard (2006, Chapter 2), and Keller (2005, Chapters 2 and 3). The exercises at the end of this book also ask for graphical summaries not fully explained here, but which are worth exploring with the help of other introductory texts or online resources.\n\n::: callout-important\n### Big picture\n\nMany graphical tools exist, but for understanding distributions and probabilities, the **histogram** plays a uniquely central role.\n:::\n\n::: callout-important\n### Chapter summary\n\nGraphical summaries provide a powerful way to explore and communicate patterns in data.\n\nDifferent types of data—cardinal, ordinal, and nominal—call for different graphical representations. Among these, the histogram plays a central role in statistics because it summarizes distributions through areas and connects naturally to ideas of probability.\n\nUnderstanding how to construct and interpret histograms, especially when class intervals are unequal, is essential for sound statistical analysis and for the topics that follow in later chapters.\n:::\n\n---\n\n## Exercises\n\n### Conceptual questions\n\n1.  Explain why graphical summaries are often more informative than tables when dealing with large data sets.\n\n2.  Give one example each of:\n\n    -   a cardinal variable,\n    -   an ordinal variable, and\n    -   a nominal variable.\n\n    Briefly explain why arithmetic operations make sense for one but not for the others.\n\n3.  Why can assigning numbers to qualitative categories be misleading if those numbers are treated as measurements?\n\n4.  A histogram shows two distributions with the same total area. What does this tell you about the data being represented?\n\n::: callout-note\n### Check your understanding\n\nIf two histograms look very different but have the same total area, what does this imply about the percentages or probabilities they represent?\n:::\n\n---\n\n### Interpreting histograms\n\n5.  Consider a histogram constructed using unequal class intervals.\n    -   Why must the vertical axis be interpreted as a *density* rather than a raw frequency?\n    -   What would go wrong if heights were drawn directly from percentages?\n6.  A histogram is right-skewed.\n    -   What does this tell you about the distribution of the data?\n    -   Give a real-world example of a variable that is likely to be right-skewed.\n7.  Explain the difference between a unimodal and a bimodal histogram.\\\n    What might cause a bimodal shape in real data?\n8.  The histogram below shows the distribution of final scores in a certain class.  \n    ![](figs/exercise/ws-2-8.png){fig-align=\"center\" width=\"50%\"}\n    -   which block represents the people who scored between 60 and 80?\n    -   Ten percent scored between 20 and 40. About what percentage scored between 40 and 60?\n    -   About what percentage scored over 60?\\\n9.A histogram of pocket-money used by EBA students in a week is shown above. No student used over Baht1,000 per month. The block over the class interval 200-500 is missing. How tall must it be?  \n    ![](figs/exercise/ws-2-9.png)\n10. The figure below shows a block of family income in a certain town. About what percent of the families in the city had incomes between Baht 15,000 and 25,000?  \n    ![](figs/exercise/ws-2-10.png){fig-align=\"center\" width=\"50%\"}\n\n::: callout-warning\n### Common pitfall\n\nStudents often confuse the *height* of bars with the *area* of bars in a histogram.\n:::\n\n---\n\n### Data structure and graphs\n\n11. For each of the following data structures, suggest an appropriate graphical summary and explain why: - cross-sectional data, - time-series data, - panel (longitudinal) data.\n12. Why is the histogram particularly important for later topics in probability and statistical inference?\n\n---\n\n### Optional challenge\n\n13. Find a real dataset (from news, government statistics, or online sources) and:\n    -   classify the variables as cardinal, ordinal, or nominal,\n    -   propose at least one appropriate graphical summary for each variable,\n    -   explain why a histogram would or would not be appropriate.\n",
    "supporting": [
      "Ch2_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}